### PR TITLE
[UNTESTED] Added Wercker integration

### PR DESCRIPTION
**Pull request by Hashfyre**
[UNTESTED]
Added test wercker integration.
The wercker app is [hashfyre/razorpay-android-sample-app](https://app.wercker.com/#applications/56bc71a853a3ee59700058eb)
(which I cannot transfer to the admin / any user for some access-related reasons)

The said Wercker application has four ENV variables:
- `SLACK_URL`
- `RZP_S3_NAME`
- `RZP_S3_ID`
- `RZP_S3_SECRET`

which have to be updated appropriately.
I am yet to test out functionality for the above mentioned reasons.

### CODE REVIEW

**Comment by shashankmehta** [comment]
Relevant: [#7](https://github.com/razorpay/razorpay-android/issues/7)

**Comment by shashankmehta** [comment]
@Hashfyre Add me as collaborator to the wercker app

**Comment by Hashfyre** [comment]
Updated `wercker.yml` with the following steps:
- Install packages: `git openjdk-7-jdk openjdk-7-jre-headless`
- Sign APK with `jarsigner`
- Align APK with `zipalign`

The wercker app needs to be updated with following `ENV_VAR`s
- `KEYSTORE_PASSWD`
- `PRIVATE_KEY_PASSWD`
- `SLACK_URL` (will need to add a new webhook intg.)

**Comment by Hashfyre** [comment]
Closing as irrelevant.

**Pull request closed without merging**
